-- Makes mounts behave like NPCs
-- for role-playing and fun.

INSERT INTO broadcast_text
(entry, male_text,                          female_text, chat_type, sound_id, language_id, emote_id1, emote_id2, emote_id3, emote_delay1, emote_delay2, emote_delay3) VALUES
(    6, 'The beast stares at you blankly.', '',                  0,        0,           0,         0,         0,         0,            0,            0,            0);

INSERT INTO conditions
(condition_entry, `type`, value1, value2, value3, value4, flags) VALUES
-- Has item (Turquoise Raptor)
(            226,      2,   8591,      1,      0,      0,     0),
-- Has item (Brown Kodo)
(            227,      2,  15290,      1,      0,      0,     0);

INSERT INTO creature_template
(entry, patch, display_id1, display_id2, display_id3, display_id4, display_scale1, display_scale2, display_scale3, display_scale4, display_probability1, display_probability2, display_probability3, display_probability4, display_total_probability, mount_display_id, name,               subname, gossip_menu_id, level_min, level_max, faction, npc_flags, speed_walk, speed_run, detection_range, call_for_help_range, leash_range, `rank`, xp_multiplier, health_multiplier, mana_multiplier, armor_multiplier, damage_multiplier, damage_variance, damage_school, base_attack_time, ranged_attack_time, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, unit_class, unit_flags, pet_family, trainer_type, trainer_spell, trainer_class, trainer_race, `type`, type_flags, loot_id, pickpocket_loot_id, skinning_loot_id, gold_min, gold_max, spell_id1, spell_id2, spell_id3, spell_id4, spell_list_id, pet_spell_list_id, spawn_spell_id, auras, ai_name, movement_type, inhabit_type, civilian, racial_leader, regeneration, equipment_id, trainer_id, vendor_id, mechanic_immune_mask, school_immune_mask, flags_extra, script_name) VALUES
(    4,     0,       11641,           0,           0,           0,              0,              0,              0,              0,                    1,                    0,                    0,                    0,                         1,                0, 'Brown Kodo',       NULL,                 4,         1,         1,      35,         1,        1.0,       1.6,            18.0,                 5.0,           0,      0,             1,                 1,               1,                1,                 1,            0.14,             0,             2000,               2000,        0,        0,          0,         0,          0,          0,          1,          0,          0,            0,             0,             0,            0,      1,          0,       0,                  0,                0,        0,        0,         0,         0,         0,         0,             0,                 0,              0, NULL,  'PetAI',             0,            1,        0,             0,            3,            0,          0,         0,                    0,                  0,           2, ''),
(    5,     0,        6472,           0,           0,           0,              0,              0,              0,              0,                    1,                    0,                    0,                    0,                         1,                0, 'Turquoise Raptor', NULL,                 5,         1,         1,      35,         1,        1.0,       1.6,            18.0,                 5.0,           0,      0,             1,                 1,               1,                1,                 1,            0.14,             0,             2000,               2000,        0,        0,          0,         0,          0,          0,          1,          0,          0,            0,             0,             0,            0,      1,          0,       0,                  0,                0,        0,        0,         0,         0,         0,         0,             0,                 0,              0, NULL,  'PetAI',             0,            1,        0,             0,            3,            0,          0,         0,                    0,                  0,           2, '');

INSERT INTO generic_scripts
(id, delay, priority, command, datalong,  datalong2, datalong3, datalong4, target_param1, target_param2, target_type, data_flags, dataint, dataint2, dataint3, dataint4, x, y,   z, o, condition_id, comments) VALUES
( 6,     0,        0,       6,        0,       0x40,         0,         0,             0,             0,           0,       0x01,       0,        0,        0,        0, 0, 0,   0, 0,            0, 'Teleport to target'),
( 6,     0,        0,       4,      152, 0x00000001,         2,         0,             0,             0,           0,          0,       0,        0,        0,        0, 0, 0,   0, 0,            0, 'Remove NPC Flag (Gossip)'),
( 6,     0,        1,       6,        0,       0x40,         0,         0,             0,             0,           0,          0,       0,        0,        0,        0, 0, 0, -10, 0,            0, 'Teleport underground'),
( 6,     0,        1,      18,      100,          0,         0,         0,             0,             0,           0,          0,       0,        0,        0,        0, 0, 0,   0, 0,            0, 'Despawn');

INSERT INTO gossip_menu
(entry, text_id, script_id, condition_id) VALUES
(    4,       4,         0,            0),
(    4,       1,         7,          227),
(    5,       4,         0,            0),
(    5,       1,         6,          226);

INSERT INTO gossip_scripts
(id, delay, priority, command, datalong, datalong2, datalong3, datalong4, target_param1, target_param2, target_type, data_flags, dataint, dataint2, dataint3, dataint4, x, y,   z, o, condition_id, comments) VALUES
( 6,     0,        0,      74,    10796,         0,         0,         0,             0,             0,           0,       0x01,       0,        0,        0,        0, 0, 0,   0, 0,            0, 'Add Aura (Turquoise Raptor)'),
( 6,     0,        0,      39,        6,         0,         0,         0,             0,             0,           0,          0,     100,        0,        0,        0, 0, 0,   0, 0,            0, 'Mount creature'),
( 7,     0,        0,      74,    18990,         0,         0,         0,             0,             0,           0,       0x01,       0,        0,        0,        0, 0, 0,   0, 0,            0, 'Add Aura (Brown Kodo)'),
( 7,     0,        0,      39,        6,         0,         0,         0,             0,             0,           0,          0,     100,        0,        0,        0, 0, 0,   0, 0,            0, 'Mount creature');

INSERT INTO npc_text
(ID, BroadcastTextID0, Probability0, BroadcastTextID1, Probability1, BroadcastTextID2, Probability2, BroadcastTextID3, Probability3, BroadcastTextID4, Probability4, BroadcastTextID5, Probability5, BroadcastTextID6, Probability6, BroadcastTextID7, Probability7) VALUES
( 4,                6,            0,                0,            0,                0,            0,                0,            0,                0,            0,                0,            0,                0,            0,                0,            0);

INSERT INTO spell_scripts
(id, delay, priority, command, datalong, datalong2, datalong3, datalong4, target_param1, target_param2, target_type, data_flags, dataint, dataint2, dataint3, dataint4, x, y, z, o, condition_id, comments) VALUES
(28,     0,        0,      93,        4,         0,         0,         0,             0,             0,           0,          0,       0,        0,        0,        0, 0, 0, 0, 0,            0, 'Call Mount (Brown Kodo)'),
(29,     0,        0,      93,        5,         0,         0,         0,             0,             0,           0,          0,       0,        0,        0,        0, 0, 0, 0, 0,            0, 'Call Mount (Turquoise Raptor)');

INSERT INTO spell_template
(entry, build, school, category, castUI, dispel, mechanic, `attributes`, attributesEx, attributesEx2, attributesEx3, attributesEx4, stances, stancesNot, targets, targetCreatureType, requiresSpellFocus, casterAuraState, targetAuraState, castingTimeIndex, recoveryTime, categoryRecoveryTime, interruptFlags, auraInterruptFlags, channelInterruptFlags, procFlags, procChance, procCharges, maxLevel, baseLevel, spellLevel, durationIndex, powerType, manaCost, manCostPerLevel, manaPerSecond, manaPerSecondPerLevel, rangeIndex, speed, modelNextSpell, stackAmount, totem1, totem2, reagent1, reagent2, reagent3, reagent4, reagent5, reagent6, reagent7, reagent8, reagentCount1, reagentCount2, reagentCount3, reagentCount4, reagentCount5, reagentCount6, reagentCount7, reagentCount8, equippedItemClass, equippedItemSubClassMask, equippedItemInventoryTypeMask, effect1, effect2, effect3, effectDieSides1, effectDieSides2, effectDieSides3, effectBaseDice1, effectBaseDice2, effectBaseDice3, effectDicePerLevel1, effectDicePerLevel2, effectDicePerLevel3, effectRealPointsPerLevel1, effectRealPointsPerLevel2, effectRealPointsPerLevel3, effectBasePoints1, effectBasePoints2, effectBasePoints3, effectBonusCoefficient1, effectBonusCoefficient2, effectBonusCoefficient3, effectMechanic1, effectMechanic2, effectMechanic3, effectImplicitTargetA1, effectImplicitTargetA2, effectImplicitTargetA3, effectImplicitTargetB1, effectImplicitTargetB2, effectImplicitTargetB3, effectRadiusIndex1, effectRadiusIndex2, effectRadiusIndex3, effectApplyAuraName1, effectApplyAuraName2, effectApplyAuraName3, effectAmplitude1, effectAmplitude2, effectAmplitude3, effectMultipleValue1, effectMultipleValue2, effectMultipleValue3, effectChainTarget1, effectChainTarget2, effectChainTarget3, effectItemType1, effectItemType2, effectItemType3, effectMiscValue1, effectMiscValue2, effectMiscValue3, effectTriggerSpell1, effectTriggerSpell2, effectTriggerSpell3, effectPointsPerComboPoint1, effectPointsPerComboPoint2, effectPointsPerComboPoint3, spellVisual1, spellVisual2, spellIconId, activeIconId, spellPriority, name,                    nameFlags, nameSubtext, nameSubtextFlags, description,                             descriptionFlags, auraDescription, auraDescriptionFlags, manaCostPercentage, startRecoveryCategory, startRecoveryTime, minTargetLevel, maxTargetLevel, spellFamilyName, spellFamilyFlags, maxAffectedTargets, dmgClass, preventionType, stanceBarOrder, dmgMultiplier1, dmgMultiplier2, dmgMultiplier3, minFactionId, minReputation, requiredAuraVision, customFlags) VALUES
(   28,  4297,      0,        0,      0,      0,        0,   0x01018110,            0,             0,             0,             0,       0,          0,       0,                  0,                  0,               0,               0,                1,            0,                    0,              0,                  0,                     0,         0,        101,           0,        0,         0,          1,             0,         0,        0,               0,             0,                     0,          1,     0,              0,           0,      0,      0,        0,        0,        0,        0,        0,        0,        0,        0,             0,             0,             0,             0,             0,             0,             0,             0,                -1,                       -1,                             0,      77,       0,       0,               0,               0,               0,               0,               0,               0,                   0,                   0,                   0,                         0,                         0,                         0,                 0,                 0,                 0,                       0,                       0,                      -1,               0,               0,               0,                      1,                      0,                      0,                      0,                      0,                      0,                  0,                  0,                  0,                   78,                    0,                    0,                0,                0,                0,                    0,                    0,                    0,                  0,                  0,                  0,               0,               0,               0,                0,                0,                0,                   0,                   0,                   0,                          0,                          0,                          0,         5160,            0,        1684,          122,             0, 'Call Brown Kodo',          983070, '',                    983068, 'Calls your rideable brown kodo.',                 983070, '',                            983070,                  0,                     0,                 0,              0,              0,               0,                0,                  0,        0,              0,             -1,              1,              0,              1,            0,             0,                  0,           0),
(   29,  4297,      0,        0,      0,      0,        0,   0x01018110,            0,             0,             0,             0,       0,          0,       0,                  0,                  0,               0,               0,                1,            0,                    0,              0,                  0,                     0,         0,        101,           0,        0,         0,          1,             0,         0,        0,               0,             0,                     0,          1,     0,              0,           0,      0,      0,        0,        0,        0,        0,        0,        0,        0,        0,             0,             0,             0,             0,             0,             0,             0,             0,                -1,                       -1,                             0,      77,       0,       0,               0,               0,               0,               0,               0,               0,                   0,                   0,                   0,                         0,                         0,                         0,                 0,                 0,                 0,                       0,                       0,                      -1,               0,               0,               0,                      1,                      0,                      0,                      0,                      0,                      0,                  0,                  0,                  0,                   78,                    0,                    0,                0,                0,                0,                    0,                    0,                    0,                  0,                  0,                  0,               0,               0,               0,                0,                0,                0,                   0,                   0,                   0,                          0,                          0,                          0,         5160,            0,        1684,          122,             0, 'Call Turquoise Raptor',    983070, '',                    983068, 'Calls your rideable turquoise raptor.',           983070, '',                            983070,                  0,                     0,                 0,              0,              0,               0,                0,                  0,        0,              0,             -1,              1,              0,              1,            0,             0,                  0,           0);
